# Converting Files For Processing and Updating

In [2]:
import numpy as np
import pandas as pd
from importlib.util import spec_from_file_location, module_from_spec
import pathlib
import re
import DLCsupport as dlcs
import xrommtools as xtc

module_path = r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\Code-Testing\data-converters.py"
spec = spec_from_file_location("dc", module_path)
dc = module_from_spec(spec)
spec.loader.exec_module(dc)

module_path = r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\Code-Testing\xrommtools.py"
spec = spec_from_file_location("xt", module_path)
xt = module_from_spec(spec)
spec.loader.exec_module(xt)

Loading DLC 3.0.0rc13...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)

#### David Bowie Trial 1

In [ ]:
# JPG TO AVI
dc.jpg_stack_to_avi(
    input_folder=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial1\Cam2"),
    output_path=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial1\Cam2.avi"),
    fps=500
)

In [9]:
# DLC TO XMALAB
xtc.dlc_to_xma(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial1\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam1DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial1\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam2DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
'NoUpdateModel',
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial1")

#### David Bowie Trial 2

In [4]:
# JPG TO AVI
dc.jpg_stack_to_avi(
    input_folder=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial2\Cam1"),
    output_path=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial2\Cam1.avi"),
    fps=500
)

{'output_path': 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\ProcessingData\\DavidBowie\\Trial2\\Cam1.avi',
 'frames_written': 6001,
 'fps': 500,
 'codec': 'MJPG',
 'width': 768,
 'height': 768}

In [9]:
# DLC TO XMALAB
xtc.dlc_to_xma(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial2\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam1DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial2\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam2DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
'NoUpdateModel',
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial2")

c:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\Code-Testing\xrommtools.py:322: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block0_values] [items->Index(['Cranium_Left_Anterior_cam1_X', 'Cranium_Left_Anterior_cam1_Y',
       'Cranium_Left_Anterior_cam2_X', 'Cranium_Left_Anterior_cam2_Y',
       'Cranium_Left_Middle_cam1_X', 'Cranium_Left_Middle_cam1_Y',
       'Cranium_Left_Middle_cam2_X', 'Cranium_Left_Middle_cam2_Y',
       'Cranium_Right_Middle_cam1_X', 'Cranium_Right_Middle_cam1_Y',
       'Cranium_Right_Middle_cam2_X', 'Cranium_Right_Middle_cam2_Y',
       'Cranium_Right_Posterior_cam1_X', 'Cranium_Right_Posterior_cam1_Y',
       'Cranium_Right_Posterior_cam2_X', 'Cranium_Right_Posterior_cam2_Y',
       'Beak_Mandible_Left_Posterior_cam1_X',
       'Beak_Mandible_Left_Posterior_cam1_Y',
       'Beak_Mandible_Left_Posterior_cam2_X',
       'Beak_Mandible_Left_Posterior_cam2_Y',
       'Beak_Mandibile_Left_Anterior_cam1_X',
       'Beak_Mandibile_Left_Anterior_cam1_Y',
       'Beak_Mandibile_Left_Anterior_cam2_X',
       'Beak_Mandibile_Left_Anterior_cam2_Y',
       'Beak_Mandible_Right_Anterior_cam1_X',
       'Beak_Mandible_Right_Anterior_cam1_Y',
       'Beak_Mandible_Right_Anterior_cam2_X',
       'Beak_Mandible_Right_Anterior_cam2_Y',
       'Beak_Maxilla_Right_Anterior_cam1_X',
       'Beak_Maxilla_Right_Anterior_cam1_Y',
       'Beak_Maxilla_Right_Anterior_cam2_X',
       'Beak_Maxilla_Right_Anterior_cam2_Y',
       'Beak_Maxilla_Right_Posterior_cam1_X',
       'Beak_Maxilla_Right_Posterior_cam1_Y',
       'Beak_Maxilla_Right_Posterior_cam2_X',
       'Beak_Maxilla_Right_Posterior_cam2_Y',
       'Beak_Maxilla_Left_Anterior_cam1_X',
       'Beak_Maxilla_Left_Anterior_cam1_Y',
       'Beak_Maxilla_Left_Anterior_cam2_X',
       'Beak_Maxilla_Left_Anterior_cam2_Y',
       'Beak_Maxilla_Left_Posterior_cam1_X',
       'Beak_Maxilla_Left_Posterior_cam1_Y',
       'Beak_Maxilla_Left_Posterior_cam2_X',
       'Beak_Maxilla_Left_Posterior_cam2_Y', 'Tongue_Lower_Palette_cam1_X',
       'Tongue_Lower_Palette_cam1_Y', 'Tongue_Lower_Palette_cam2_X',
       'Tongue_Lower_Palette_cam2_Y', 'Glottis_cam1_X', 'Glottis_cam1_Y',
       'Glottis_cam2_X', 'Glottis_cam2_Y', 'Superior_Trachea_cam1_X',
       'Superior_Trachea_cam1_Y', 'Superior_Trachea_cam2_X',
       'Superior_Trachea_cam2_Y', 'Keel_Dorsal_Anterior_cam1_X',
       'Keel_Dorsal_Anterior_cam1_Y', 'Keel_Dorsal_Anterior_cam2_X',
       'Keel_Dorsal_Anterior_cam2_Y', 'Keel_Dorsal_Posterior_cam1_X',
       'Keel_Dorsal_Posterior_cam1_Y', 'Keel_Dorsal_Posterior_cam2_X',
       'Keel_Dorsal_Posterior_cam2_Y', 'Keel_Inferior_cam1_X',
       'Keel_Inferior_cam1_Y', 'Keel_Inferior_cam2_X', 'Keel_Inferior_cam2_Y',
       'Pelvis_Right_Inferior_cam1_X', 'Pelvis_Right_Inferior_cam1_Y',
       'Pelvis_Right_Inferior_cam2_X', 'Pelvis_Right_Inferior_cam2_Y',
       'Pelvis_Right_Superior_cam1_X', 'Pelvis_Right_Superior_cam1_Y',
       'Pelvis_Right_Superior_cam2_X', 'Pelvis_Right_Superior_cam2_Y',
       'Pelvis_Left_Superior_cam1_X', 'Pelvis_Left_Superior_cam1_Y',
       'Pelvis_Left_Superior_cam2_X', 'Pelvis_Left_Superior_cam2_Y',
       'Pelvis_Left_Inferior_cam1_X', 'Pelvis_Left_Inferior_cam1_Y',
       'Pelvis_Left_Inferior_cam2_X', 'Pelvis_Left_Inferior_cam2_Y'],
      dtype='object')]

  df.to_hdf(h5_save_path, key="df_with_missing", mode="w")

#### David Bowie Trial 3

In [6]:
# JPG TO AVI
dc.jpg_stack_to_avi(
    input_folder=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial3\Cam2"),
    output_path=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial3\Cam2.avi"),
    fps=500
)

{'output_path': 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\ProcessingData\\DavidBowie\\Trial3\\Cam2.avi',
 'frames_written': 6001,
 'fps': 500,
 'codec': 'MJPG',
 'width': 768,
 'height': 768}

In [10]:
# DLC TO XMALAB
xtc.dlc_to_xma(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial3\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam1DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial3\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam2DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
'NoUpdateModel',
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial3")

#### David Bowie Trial 4

In [8]:
# JPG TO AVI
dc.jpg_stack_to_avi(
    input_folder=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial4\Cam2"),
    output_path=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial4\Cam2.avi"),
    fps=500
)

{'output_path': 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\ProcessingData\\DavidBowie\\Trial4\\Cam2.avi',
 'frames_written': 6001,
 'fps': 500,
 'codec': 'MJPG',
 'width': 768,
 'height': 768}

In [11]:
# DLC TO XMALAB
xtc.dlc_to_xma(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial4\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam1DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial4\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam2DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
'NoUpdateModel',
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial4")

#### David Bowie Trial 5

In [4]:
# JPG TO AVI
dc.jpg_stack_to_avi(
    input_folder=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial5\Cam2"),
    output_path=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial5\Cam2.avi"),
    fps=500
)
# JPG TO AVI
dc.jpg_stack_to_avi(
    input_folder=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial5\Cam1"),
    output_path=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial5\Cam1.avi"),
    fps=500
)

{'output_path': 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\ProcessingData\\DavidBowie\\Trial5\\Cam1.avi',
 'frames_written': 6001,
 'fps': 500,
 'codec': 'MJPG',
 'width': 768,
 'height': 768}

In [8]:

# DLC TO XMALAB
xtc.dlc_to_xma(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial5\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam1DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial5\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam2DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
'NoUpdateModel',
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial5")

#### David Bowie Trial 6

In [5]:
# JPG TO AVI
dc.jpg_stack_to_avi(
    input_folder=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial6\Cam2"),
    output_path=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial6\Cam2.avi"),
    fps=500
)
# JPG TO AVI
dc.jpg_stack_to_avi(
    input_folder=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial6\Cam1"),
    output_path=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial6\Cam1.avi"),
    fps=500
)

{'output_path': 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\ProcessingData\\DavidBowie\\Trial6\\Cam1.avi',
 'frames_written': 6001,
 'fps': 500,
 'codec': 'MJPG',
 'width': 768,
 'height': 768}

In [9]:

# DLC TO XMALAB
xtc.dlc_to_xma(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial6\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam1DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial6\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam2DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
'NoUpdateModel',
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial6")

#### David Bowie Trial 7

In [6]:
# JPG TO AVI
dc.jpg_stack_to_avi(
    input_folder=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial7\Cam2"),
    output_path=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial7\Cam2.avi"),
    fps=500
)
# JPG TO AVI
dc.jpg_stack_to_avi(
    input_folder=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial7\Cam1"),
    output_path=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial7\Cam1.avi"),
    fps=500
)

{'output_path': 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\ProcessingData\\DavidBowie\\Trial7\\Cam1.avi',
 'frames_written': 6001,
 'fps': 500,
 'codec': 'MJPG',
 'width': 768,
 'height': 768}

In [10]:

# DLC TO XMALAB
xtc.dlc_to_xma(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial7\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam1DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial7\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam2DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
'NoUpdateModel',
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial7")

#### David Bowie Trial 8

In [7]:
# JPG TO AVI
dc.jpg_stack_to_avi(
    input_folder=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial8\Cam2"),
    output_path=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial8\Cam2.avi"),
    fps=500
)
# JPG TO AVI
dc.jpg_stack_to_avi(
    input_folder=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial8\Cam1"),
    output_path=pathlib.Path(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial8\Cam1.avi"),
    fps=500
)

{'output_path': 'C:\\Users\\Salle-Cineradio\\Documents\\MachineLearning\\BirdSongs-MNHN\\Testing\\ProcessingData\\DavidBowie\\Trial8\\Cam1.avi',
 'frames_written': 6001,
 'fps': 500,
 'codec': 'MJPG',
 'width': 768,
 'height': 768}

In [12]:

# DLC TO XMALAB
xtc.dlc_to_xma(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial8\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam1DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial8\post_processed_data_CanariMay22-trainset95shuffle1_200\Cam2DLC_Resnet50_CanariMay22shuffle1_snapshot_200.csv",
'NoUpdateModel',
r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial8")

In [24]:
corrected_data = pd.read_csv(r"C:\Users\Salle-Cineradio\Documents\MachineLearning\BirdSongs-MNHN\Testing\ProcessingData\DavidBowie\Trial8\active_updates\dino\data\corrections_autosave.csv")
corrected_data

     frame_id camera                      bodypart  x_corrected  y_corrected
0        2816   cam1  Beak_Mandibile_Left_Anterior        314.0        283.0
1        2816   cam1  Beak_Mandible_Left_Posterior        317.0        276.0
2        2816   cam1  Beak_Mandible_Right_Anterior        301.0        286.0
3        2816   cam1    Beak_Maxilla_Left_Anterior        319.0        293.0
4        2816   cam1   Beak_Maxilla_Left_Posterior        324.0        292.0
..        ...    ...                           ...          ...          ...
701      5348   cam2                 Keel_Inferior        492.0        508.0
702      5348   cam2         Pelvis_Right_Inferior        585.0        498.0
703      5348   cam2         Pelvis_Right_Superior        571.0        481.0
704      5348   cam2              Superior_Trachea        428.0        354.0
705      5348   cam2          Tongue_Lower_Palette        397.0        322.0

[706 rows x 5 columns]

### Retraining Models

In [25]:
wide = (
    corrected_data.pivot(
        index=["frame_id", "camera"],
        columns="bodypart",
        values=["x_corrected", "y_corrected"]
    )
)

wide.columns = [
    f"{bp}_{coord.replace('_corrected','')}"
    for coord, bp in wide.columns
]

wide = wide.reset_index()
display(wide)

,frame_id,camera,Beak_Mandibile_Left_Anterior_x,Beak_Mandible_Left_Posterior_x,Beak_Mandible_Right_Anterior_x,Beak_Maxilla_Left_Anterior_x,Beak_Maxilla_Left_Posterior_x,Beak_Maxilla_Right_Anterior_x,Beak_Maxilla_Right_Posterior_x,Cranium_Left_Anterior_x,...,Glottis_y,Keel_Dorsal_Anterior_y,Keel_Dorsal_Posterior_y,Keel_Inferior_y,Pelvis_Left_Inferior_y,Pelvis_Left_Superior_y,Pelvis_Right_Inferior_y,Pelvis_Right_Superior_y,Superior_Trachea_y,Tongue_Lower_Palette_y
0,2816,cam1,314.0,317.0,301.0,319.0,324.0,304.0,304.0,311.0,...,320.0,417.0,423.0,454.0,431.0,428.0,448.0,432.0,325.0,301.0
1,2816,cam2,321.0,332.0,328.0,326.0,344.0,334.0,348.0,400.0,...,353.0,460.0,466.0,NaN,485.0,481.0,498.0,NaN,356.0,329.0
2,2894,cam1,314.0,317.0,301.0,320.0,324.0,305.0,304.0,310.0,...,320.0,NaN,NaN,NaN,431.0,NaN,448.0,432.0,325.0,304.0
3,2894,cam2,323.0,333.0,329.0,327.0,347.0,336.0,349.0,NaN,...,NaN,460.0,468.0,NaN,NaN,NaN,498.0,NaN,NaN,332.0
4,3158,cam1,327.0,330.0,314.0,331.0,335.0,316.0,313.0,321.0,...,318.0,417.0,423.0,454.0,432.0,429.0,448.0,432.0,324.0,300.0
5,3158,cam2,326.0,336.0,331.0,329.0,350.0,337.0,350.0,NaN,...,NaN,459.0,467.0,NaN,485.0,482.0,499.0,NaN,NaN,NaN
6,3705,cam1,329.0,332.0,315.0,333.0,338.0,318.0,315.0,NaN,...,320.0,418.0,425.0,455.0,432.0,428.0,448.0,432.0,326.0,302.0
7,3705,cam2,327.0,338.0,333.0,332.0,352.0,337.0,352.0,409.0,...,352.0,461.0,469.0,NaN,NaN,NaN,496.0,NaN,359.0,330.0
8,3902,cam1,329.0,333.0,317.0,335.0,339.0,319.0,316.0,323.0,...,320.0,417.0,424.0,455.0,431.0,429.0,448.0,432.0,326.0,301.0
9,3902,cam2,328.0,339.0,332.0,332.0,352.0,339.0,351.0,NaN,...,NaN,461.0,NaN,NaN,485.0,481.0,499.0,481.0,NaN,330.0
10,4055,cam1,342.0,344.0,328.0,346.0,348.0,330.0,326.0,333.0,...,321.0,417.0,423.0,454.0,432.0,428.0,448.0,431.0,326.0,303.0
11,4055,cam2,330.0,342.0,335.0,336.0,356.0,341.0,353.0,408.0,...,353.0,462.0,466.0,505.0,484.0,481.0,497.0,482.0,358.0,331.0
12,4116,cam1,343.0,345.0,329.0,347.0,350.0,330.0,326.0,334.0,...,322.0,418.0,425.0,455.0,432.0,428.0,448.0,432.0,326.0,303.0
13,4116,cam2,327.0,338.0,331.0,333.0,353.0,338.0,350.0,NaN,...,NaN,464.0,469.0,NaN,484.0,480.0,498.0,NaN,NaN,333.0
14,4204,cam1,342.0,345.0,328.0,346.0,349.0,330.0,326.0,335.0,...,324.0,417.0,423.0,455.0,432.0,429.0,448.0,432.0,322.0,291.0
15,4204,cam2,316.0,327.0,320.0,321.0,342.0,328.0,340.0,395.0,...,357.0,461.0,467.0,NaN,485.0,NaN,499.0,NaN,355.0,NaN
16,4206,cam1,342.0,345.0,328.0,346.0,349.0,330.0,326.0,335.0,...,324.0,417.0,423.0,455.0,432.0,NaN,448.0,432.0,322.0,289.0
17,4206,cam2,315.0,326.0,320.0,321.0,341.0,326.0,340.0,395.0,...,356.0,461.0,467.0,NaN,NaN,482.0,500.0,NaN,355.0,317.0
18,4323,cam1,306.0,313.0,295.0,311.0,319.0,297.0,297.0,325.0,...,309.0,NaN,423.0,454.0,432.0,429.0,449.0,433.0,308.0,268.0
19,4323,cam2,321.0,331.0,329.0,322.0,340.0,332.0,346.0,NaN,...,338.0,463.0,467.0,505.0,NaN,NaN,500.0,NaN,339.0,NaN
20,4324,cam1,307.0,313.0,295.0,310.0,319.0,297.0,297.0,326.0,...,309.0,NaN,423.0,454.0,432.0,429.0,449.0,433.0,308.0,268.0
21,4324,cam2,321.0,331.0,329.0,323.0,340.0,333.0,346.0,NaN,...,339.0,462.0,466.0,NaN,NaN,NaN,499.0,483.0,338.0,293.0
22,4520,cam1,299.0,305.0,288.0,303.0,312.0,290.0,290.0,319.0,...,NaN,416.0,421.0,453.0,432.0,428.0,448.0,432.0,314.0,282.0
23,4520,cam2,331.0,342.0,340.0,334.0,351.0,344.0,357.0,415.0,...,339.0,460.0,467.0,504.0,NaN,481.0,500.0,481.0,345.0,308.0
24,4642,cam1,301.0,308.0,290.0,305.0,314.0,292.0,292.0,321.0,...,310.0,415.0,422.0,454.0,431.0,428.0,447.0,432.0,315.0,284.0
25,4642,cam2,333.0,343.0,341.0,336.0,353.0,346.0,360.0,NaN,...,340.0,460.0,465.0,503.0,NaN,NaN,497.0,481.0,NaN,311.0
26,4793,cam1,341.0,344.0,328.0,345.0,348.0,329.0,326.0,332.0,...,NaN,417.0,421.0,455.0,430.0,NaN,446.0,432.0,NaN,285.0
27,4793,cam2,343.0,355.0,346.0,345.0,365.0,350.0,362.0,NaN,...,NaN,460.0,464.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,5098,cam1,339.0,342.0,326.0,343.0,346.0,327.0,323.0,330.0,...,NaN,415.0,420.0,452.0,431.0,428.0,448.0,431.0,NaN,286.0
29,5098,cam2,343.0,356.0,347.0,346.0,366.0,351.0,362.0,431.0,...,344.0,457.0,464.0,503.0,484.0,481.0,499.0,480.0,NaN,315.0
30,5116,cam1,339.0,342.0,326.0,344.0,346.0,328.0,324.0,330.0,...,313.0,415.0,421.0,453.0,431.0,NaN,447.0,431.0,320.0,286.0
31,5116,cam2,343.0,355.0,346.0,345.0,365.0,349.0,362.0,NaN,...,NaN,460.0,464.0,NaN,NaN,NaN,497.0,480.0,NaN,NaN
32,5206,cam1,334.0,336.0,320.0,337.0,342.0,322.0,319.0,329.0,...,316.0,415.0,421.0,453.0,431.0,428.0,447.0,432.0,321.0,293.0
33,5206,cam2,339.0,351.0,344.0,343.0,363.0,349.0,362.0,423.0,...,NaN,461.0,466.0,505.0,485.0,NaN,499.0,NaN,NaN,NaN
34,5265,cam1,326.0,330.0,313.0,330.0,336.0,315.0,313.0,327.0,...,318.0,415.0,422.0,454.0,431.0,427.0,447.0,431.0,323.0,299.0
35,5265,cam2,334.0,344.0,340.0,338.0,358.0,346.0,360.0,414.0,...,NaN,458.0,466.0,NaN,482.0,NaN,496.0,480.0,NaN,327.0
36,5324,cam1,327.0,331.0,314.0,332.0,337.0,316.0,315.0,330.0,...,320.0,417.0,423.0,455.0,430.0,427.0,446.0,431.0,323.0,293.0
37,5324,cam2,330.0,341.0,336.0,334.0,354.0,343.0,356.0,NaN,...,353.0,460.0,467.0,NaN,484.0,480.0,496.0,479.0,355.0,323.0
38,5348,cam1,327.0,331.0,314.0,332.0,338.0,317.0,315.0,330.0,...,321.0,417.0,423.0,455.0,430.0,427.0,446.0,431.0,321.0,293.0
39,5348,cam2,329.0,339.0,335.0,333.0,353.0,341.0,355.0,409.0,...,NaN,461.0,467.0,508.0,NaN,NaN,498.0,481.0,354.0,322.0